'use strict';

module.exports = {
	struct: {
		scale: [
			['double', 'domain', 4],
			['double', 'm', 3],
			['double', 'b', 3],
			['int', 'count'],
			['uint32_t', 'range', 4]]
	},
	enum: {
		type: ['LOG', 'LINEAR', 'ORDINAL']
	},
	includes: ['<stdint.h>']
}
