'use strict';

module.exports = {
	struct: {
		search_result: [
			['uint32_t', 'count'],
			['uint32_t *', 'matches']]
	},
	enum: {
		search_type: ['EXACT', 'CONTAINS']
	},
	includes: ['<stdint.h>']
};
